import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Kannada } from "next/font/google";
import "./globals.scss";
import "./utils.scss";
import { StoreProvider } from "@/redux/StoreProvider";
import ThemeRegistry from "@/ThemeRegistry/ThemeRegistry";

import Sidebar from "./ClientComponents/Sidebar/Sidebar";
import Header from "./ClientComponents/Header/Header";
import Footer from "./ClientComponents/Footer/Footer";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";



const notoKannada = Noto_Sans_Kannada({
  variable: "--font-noto-kannada",
  subsets: ["kannada"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoKannada.variable} ${notoKannada.variable}`}>
        <ThemeRegistry>
          <StoreProvider>
            <Header />
            <div>
              {/* <Sidebar/> */}
              {children}
            </div>
            <Footer />
          </StoreProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}